version: '3'
services:
  mysql:
    image: mysql:8.0.25
    container_name: gb-mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode="" --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: '1'
      MYSQL_DATABASE: 'gb'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: '1'
      LANG: C.UTF-8
    volumes:
      - '.mysql:/var/lib/mysql'
    ports:
      - '3336:3306'
